### ISSUE TITLE
Review G07: Banner Entity.

### ISSUE THREAD

**Issue by rafcasceb** [rafcasceb/Acme-SF-D01#115]
Mover a paquete acme.
@Transient al método derivado.
Las validaciones del constructor nuevo creo que deberían ir antes de asignar los atributos, porque si no, aunque tire error puede ser que se hayan guardado ya.

**Comment by luimeldia** [comment]
Mover a paquete acme. ✅
@transient al método derivado. ✅

En cuanto a lo del constructor tengo entendido que en java, si dentro de un constructor salta una excepcion, la instancia no llega a crearse.
